# Generated by Django 2.2 on 2020-07-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todoListCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
        migrations.AlterModelTable(
            name='todolist',
            table=None,
        ),
        migrations.AddField(
            model_name='todolist',
            name='listName',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='todo.todoListCollect'),
            preserve_default=False,
        ),
    ]
