# Generated by Django 2.2 on 2020-07-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200714_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='listName',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='todo.todoListCollect'),
        ),
        migrations.AlterField(
            model_name='todolistcollect',
            name='listName',
            field=models.CharField(default='default', max_length=256),
        ),
    ]
