# Generated by Django 2.2 on 2020-07-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200714_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='listName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todoListCollect'),
        ),
    ]
