# Generated by Django 2.2 on 2020-09-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200714_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='todolistcollect',
            options={'managed': False},
        ),
    ]
